NUMPY OPERATIONS

In [2]:
import numpy as np


In [3]:
q1 = np.array([
    [200, 220, 250],  # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360]   # Product C
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])

In [4]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [5]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [7]:
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])

In [8]:
revenue = q1*prices
revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [9]:
discounts = prices*(2/100)
discounts

array([[0.2 , 0.24, 0.22],
       [0.16, 0.18, 0.2 ],
       [0.3 , 0.32, 0.34]])

In [10]:
total_disc_given = discounts*q1
total_disc_given

array([[ 40. ,  52.8,  55. ],
       [ 24. ,  32.4,  42. ],
       [ 90. , 105.6, 122.4]])

In [11]:
# first column is square footage, second is bedrooms
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights = np.array([150, 50000])

price = np.dot(features, weights)
price

array([450000, 370000])

NUMPY STACKING AND SLICING

In [12]:
a = np.array([2,3,4,5,6,7,8,9])

In [13]:
a[0:4]

array([2, 3, 4, 5])

In [14]:
a[-1]

np.int64(9)

In [15]:
a[:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[:4]

array([2, 3, 4, 5])

In [17]:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

In [18]:
b[:2,1:]

array([[2, 3],
       [5, 6]])

In [19]:
b[1]

array([4, 5, 6])

In [20]:
b[-1]

array([7, 8, 9])

In [21]:
b[-1,-1]

np.int64(9)

In [22]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

In [23]:
amount = transactions[:,2]
amount

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [24]:
max_amount = np.argmax(amount)
transactions[max_amount]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [25]:
transactions[transactions[:,1] == 'Aryan']

array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

NUMPY METHODS


In [41]:
rev = np.array(([11,22,45,13,33],[44,76,33,44,85]))
rev

array([[11, 22, 45, 13, 33],
       [44, 76, 33, 44, 85]])

In [27]:
rev.flatten()

array([11, 22, 45, 13, 33, 44, 76, 33, 44, 85])

In [30]:
rev[1,3]=55
rev

array([[11, 22, 45, 13, 33],
       [44, 76, 33, 55, 85]])

In [31]:
rev.shape

(2, 5)

In [32]:
rev.size

10

In [42]:
np.sort(rev,axis=1)

array([[11, 13, 22, 33, 45],
       [33, 44, 44, 76, 85]])

In [38]:
rev

array([[11, 13, 22, 33, 45],
       [33, 44, 55, 76, 85]])